### PR TITLE
Feature r51 change header andrew melntchuk

### PR DESCRIPTION
**Pull request by andrew-melnychuk**
## Click Up

* [#R51](https://app.clickup.com/t/c50hhn)
* [#R54](https://app.clickup.com/t/c50jak)

## Summary of issue

Old fashion header and footer

## Summary of change

Changed Header and Footer according to new UI

## Testing approach

manual
unit

### CODE REVIEW

**Review by Romanarkko — DISMISSED** [review]
LGFM

**Review by Katy-dev — DISMISSED** [review]

**Comment by Katy-dev** [comment]
Approved

**Review by Rominos7 — DISMISSED** [review]
Good

**Review by Romanarkko — APPROVED** [review]
LGFM

**Review by Rominos7 — APPROVED** [review]
Good

**Review by Katy-dev — APPROVED** [review]
approved

**Pull request merged**
