### PR TITLE
Feature #r44 create login page larysa shashuk

### PR DESCRIPTION
**Pull request by LarysaShashuk**
dev
## ClickUp
https://app.clickup.com/t/brx80g

## Summary of issue

Created Login Page

## Summary of change

- added login form, login page component
- reset browser user agent style for inputs
- added padding to login and register pages. In order for them to be placed with the same padding from the header component.
- added common buttons style for form button component

### CODE REVIEW

**Review by Katy-dev — DISMISSED** [review]
approved

**Review by Katy-dev — APPROVED** [review]
Approved

**Review by andrew-melnychuk — APPROVED** [review]
good

**Review by Rominos7 — APPROVED** [review]
Good

**Pull request merged**
