### PR TITLE
added fonts, images, scss variables according to UI design

### PR DESCRIPTION
**Pull request by LarysaShashuk**
dev
## ClickUp

https://app.clickup.com/t/az124y

## Summary of change

added fonts, images, scss variables according to UI design

## Testing approach

manually

### CODE REVIEW

**Review by andrew-melnychuk — DISMISSED** [review]
good

**Review by Katy-dev — DISMISSED** [review]
approved

**Review by Romanarkko — APPROVED** [review]
Approve

**Review by Katy-dev — APPROVED** [review]

**Review by andrew-melnychuk — APPROVED** [review]
good

**Pull request merged**
