### PR TITLE
Feature #R69 Katya Nemerovetska

### PR DESCRIPTION
**Pull request by Katy-dev**
dev
## Click UP

https://app.clickup.com/t/cuz5ee

## Summary of issue

created selected for school

## Summary of change

added test to university card component and user option

## Testing approach

jest

### CODE REVIEW

**Review by LarysaShashuk — DISMISSED** [review]
done

**Review by andrew-melnychuk — DISMISSED** [review]
good

**Review by andrew-melnychuk — APPROVED** [review]
good

**Review by LarysaShashuk — APPROVED** [review]
done

**Review by Rominos7 — APPROVED** [review]
Good

**Pull request merged**
