### PR TITLE
Feature #r33 add form input tests larysa shashuk

### PR DESCRIPTION
**Pull request by LarysaShashuk**
dev
## ClickUp

https://app.clickup.com/t/brx9ac

## Summary of change
- formButton component test
- formButtonClose component test
- formInput component test
- formInputError component test
- login/register pages style (padding-bottom, height)

### CODE REVIEW

**Review by Katy-dev — DISMISSED** [review]
good

**Review by Katy-dev — APPROVED** [review]

**Comment by Katy-dev** [comment]
good

**Review by Rominos7 — APPROVED** [review]
Good

**Review by andrew-melnychuk — APPROVED** [review]
good

**Pull request merged**
