### PR TITLE
Feature r59 profile form hook andrew melnychuk

### PR DESCRIPTION
**Pull request by andrew-melnychuk**
dev
## ClickUp

* [R59](https://app.clickup.com/t/c50yuq)

## Summary of issue

UseProfile hook
header style

## Summary of change

UseProdile hook
header restyle

## Testing approach

manual
unit

### CODE REVIEW

**Review by Rominos7 — APPROVED** [review]
Good

**Review by Katy-dev — APPROVED** [review]
Approved

**Review by Katy-dev — APPROVED** [review]

**Review by Romanarkko — APPROVED** [review]
LGFM

**Review by Rominos7 — APPROVED** [review]
Good

**Pull request merged**
