### PR TITLE
Feature #r28 Katya Nemerovetska

### PR DESCRIPTION
**Pull request by Katy-dev**
dev
## Click Up
https://app.clickup.com/t/bev0va

## Summary of issue
the component of style was fixed

## Summary of change
fix style

## Testing approach
 Unit testing

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=90%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

### CODE REVIEW

**Review by andrew-melnychuk — APPROVED** [review]
good

**Review by LarysaShashuk — APPROVED** [review]
Done

**Comment by Romanarkko** [comment]
Approve

**Review by Romanarkko — APPROVED** [review]
Approve

**Pull request merged**
