### PR TITLE
Feature #55 katya nemerovetska

### PR DESCRIPTION
**Pull request by Katy-dev**
dev

## Click Up

https://app.clickup.com/t/c50jnq

## Summary of issue

Implement user profile component

## Summary of change

implement component userOption,
wrote test to component,
fixed style formInput component,
created  and styled formInputProfile

## Testing approach

Jest testing

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=90%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

### CODE REVIEW

**Review by Rominos7 — DISMISSED** [review]
Good

**Review by Romanarkko — DISMISSED** [review]
Good

**Review by andrew-melnychuk — APPROVED** [review]
good

**Review by Romanarkko — APPROVED** [review]
good

**Review by Rominos7 — APPROVED** [review]
Good

**Pull request merged**
