### PR TITLE
Feature #r30 implement UI style filter roman serhiychuk

### PR DESCRIPTION
**Pull request by Rominos7**
ClickUp
#R30 Implement UI style-> filter

## Summary of issue
Implement UI style to component - filter

## Summary of change

1) Implemented UI style to component - filter
2) Moved 404 page to folder "/pages"
3) Added Route when we write wrong path (exp. /dsfsdfdsf) it will redirect us to page 404
4) Minor bux fix

### CODE REVIEW

**Review by LarysaShashuk — DISMISSED** [review]
Approved

**Review by Katy-dev — DISMISSED** [review]
approved

**Review by Romanarkko — COMMENTED** [review]
1. There are merge conflicts in svg files.
2. You changed folder name and file name of errorIndicator, and dont change in Error boundry, it will not work now

**Review by Katy-dev — APPROVED** [review]
Approved

**Review by LarysaShashuk — APPROVED** [review]
approved

**Review by Romanarkko — APPROVED** [review]
Approve

**Pull request merged**
